class StringCons{

  static String a='';
  static String internetDisconnectTitle='You seem to be offline';
  static String internetDisconnectDescription='Please check your internet connection to continue using the application';
  static String platinumAdContent='Start with higher investment and risk for a 50% expected annual ROI.';
  static String goldAdTitle='ULTIMATE PRODUCTS';
  static String goldAdDescription='Supreme boosts up to 40% ROI with a 50% risk profile, while Elite shines with up to 50% ROI at the same risk level. An adjustable risk ratio is the game changer that redefines money and risk management for you. Invest with confidence and control like never before!';
  static String platinumAdTitle='PLATINUM PRODUCT';
  static String platinumAdDescription='Start With High-Sale Investment And Risk For A Whopping 50% Or More Expected Annual ROI. You Can Allow The Freedom Trading Engine To Automatically Open Multiple Trades In Different Trading Groups Of High, Medium And Low Risks. You Will Also Get Early Access To Extended Sub-Products.';
  static String token='eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJvaWQiOiI1YzBjNDVmZi0zNGQ0LTQwN2UtYmRlOC1lNTI2YWJhNTViZTMiLCJzdWIiOiI1YzBjNDVmZi0zNGQ0LTQwN2UtYmRlOC1lNTI2YWJhNTViZTMiLCJuYW1lIjoidW5rbm93biIsImVtYWlscyI6WyJmb3JtYXQwMUBtYWlsaW5hdG9yLmNvbSJdLCJzY3AiOiJVc2VyLlJlYWRBbGwiLCJhenAiOiIyMzUzMDUyYS01YzZiLTQ5ODItYjBmZC1lNzI3NWU0MjM0YzUiLCJ2ZXIiOiIxLjAiLCJpYXQiOjE2OTgyMTE4NTYsImF1ZCI6IjIzNTMwNTJhLTVjNmItNDk4Mi1iMGZkLWU3Mjc1ZTQyMzRjNSIsImV4cCI6MTY5ODIxOTA1NiwiaXNzIjoiaHR0cHM6Ly9teWZyZWVkb21sdGQuYjJjbG9naW4uY29tLzVlN2JkMWY5LWQ5NTMtNDk1YS05OGQ3LTI0NzYzMTk0ODRmMi92Mi4wLyIsIm5iZiI6MTY5ODIxMTg1Nn0.gnmfY4zUUbQ36gwUnOfTaYrNyZHZ9Cr2O-83zbect3VjcOJNUDftdt3jWoe2hupZHOfVo_no8hLfTCxH6qMA_wqZRScRK8b5h5MhIenhtTuf0y2IQuBFHhK6CF3qYrDiMoFBnX81XDd2QgjfmBb8fwPoS4gA5d7DgF-eSxODFlfGP7IfooxLejrLBgDJXb6thH7OEX1-WmPOJvIco1fTMrA5cpu6pAFHgbvw2bLo4S1CewJMAIpGrdc3sTzVRNV5fwa_NDi3dZBGCh7XdAcFxzTD5C8CIVLTGIWuvQmOGKjk8-y_FmkRMCpS3t9ox3lk84AzB1tIoFf1Jouo4_OwCg';
  // static String token='eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJ2ZXIiOiIxLjAiLCJpc3MiOiJodHRwczovL215ZnJlZWRvbWx0ZC5iMmNsb2dpbi5jb20vNWU3YmQxZjktZDk1My00OTVhLTk4ZDctMjQ3NjMxOTQ4NGYyL3YyLjAvIiwic3ViIjoiNWMwYzQ1ZmYtMzRkNC00MDdlLWJkZTgtZTUyNmFiYTU1YmUzIiwiYXVkIjoiMjM1MzA1MmEtNWM2Yi00OTgyLWIwZmQtZTcyNzVlNDIzNGM1IiwiZXhwIjoxNjk1ODQxMDQ1LCJhY3IiOiJiMmNfMV9zaWdudXBzaWduaW4iLCJub25jZSI6ImRlZmF1bHROb25jZSIsImlhdCI6MTY5NTgzMzg0NSwiYXV0aF90aW1lIjoxNjk1ODMzODQ1LCJuYW1lIjoidW5rbm93biIsImVtYWlscyI6WyJmb3JtYXQwMUBtYWlsaW5hdG9yLmNvbSJdLCJuYmYiOjE2OTU4MzM4NDV9.fHp0TZJxMdwQc28_mvAhOmfgLCe7ep5LxEAL-r1mPlpoq0-QiZg4NjqU2ZHyw6h8Mr43yIHGdy4v7jZKKnLz5Rb_MV8-h0nygmXYI-gzoUL_XVE7SN65ytwQ3u2k-SCC0FSgdnVHUNuyC1ttM2B4LbI_K1qbtg7-rEJjQEZz6vWWY5DWjA6AuJlZqrtUmhnZisKYyRanqWAzJrncMjt5d-m1zvpcFRFVMCGge9Oqz5nnzV58CcPCfUxmIAcYXMGnxhsz2mVNT7goDkhL7abUGmLvQWJ8samn45u_lda19hsv62P9lWEA3g1qQQLbkr4dYcS5kIayIcEoYVH5HWqKbA';
  // static String token='eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJvaWQiOiI1YzBjNDVmZi0zNGQ0LTQwN2UtYmRlOC1lNTI2YWJhNTViZTMiLCJzdWIiOiI1YzBjNDVmZi0zNGQ0LTQwN2UtYmRlOC1lNTI2YWJhNTViZTMiLCJuYW1lIjoidW5rbm93biIsImVtYWlscyI6WyJmb3JtYXQwMUBtYWlsaW5hdG9yLmNvbSJdLCJzY3AiOiJVc2VyLlJlYWRBbGwiLCJhenAiOiIyMzUzMDUyYS01YzZiLTQ5ODItYjBmZC1lNzI3NWU0MjM0YzUiLCJ2ZXIiOiIxLjAiLCJpYXQiOjE2OTUwMjA5NTAsImF1ZCI6IjIzNTMwNTJhLTVjNmItNDk4Mi1iMGZkLWU3Mjc1ZTQyMzRjNSIsImV4cCI6MTY5NTAyODE1MCwiaXNzIjoiaHR0cHM6Ly9teWZyZWVkb21sdGQuYjJjbG9naW4uY29tLzVlN2JkMWY5LWQ5NTMtNDk1YS05OGQ3LTI0NzYzMTk0ODRmMi92Mi4wLyIsIm5iZiI6MTY5NTAyMDk1MH0.WhGZAcrIKlPx5-FYmXvMKoWuwHZNf8AzhRSG5B2ouznnXIxOuMyQZoK-fQiph_zFm9GhS3H51Qn3WW1LiWh7S6bx0zWP2s7u2t9ZCI1UHzzHmqpvMH5ZOJmLf9a-CeQkV_jc1UxgNLi-tl8o7XX7JReIUtv3MFS-44E1GNMjS0OWrmdnXyFNnPyU3mpkQly8k8nCQwzmzIv-_vRdI_twK6iQ7bcu-PMCCMez29-WFlfthv2GbrJrZvjAWwx80VwR7sLWczoKVccIdANzUW3pJwIbso6uYhujWxUSiWO4sRCtVYQfQkRYsNNlMjrtr8GkorGxBhozjddwNF-U8WpbPA';
  static String tokenTemp='eyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJ2ZXIiOiIxLjAiLCJpc3MiOiJodHRwczovL215ZnJlZWRvbWx0ZC5iMmNsb2dpbi5jb20vNWU3YmQxZjktZDk1My00OTVhLTk4ZDctMjQ3NjMxOTQ4NGYyL3YyLjAvIiwic3ViIjoiNzY3Y2UyNjYtYzAxOS00ZGE4LWE3ZjQtMjA3YjhiODZmNmMyIiwiYXVkIjoiMjM1MzA1MmEtNWM2Yi00OTgyLWIwZmQtZTcyNzVlNDIzNGM1IiwiZXhwIjoxNjk0NzEzNjE3LCJhY3IiOiJiMmNfMV9zaWdudXBzaWduaW4iLCJub25jZSI6ImRlZmF1bHROb25jZSIsImlhdCI6MTY5NDcwNjQxNywiYXV0aF90aW1lIjoxNjk0NzA2NDE3LCJuYW1lIjoidW5rbm93biIsImVtYWlscyI6WyJxdWluQHZtYW5pLmNvbSJdLCJuYmYiOjE2OTQ3MDY0MTd9.o3OYfL6XDMddFgZGl8c_apUjNW1G6-rKqtI3f9plgTRdbVdRkojt9PxUPVP4_GY_8K8kYTYX68fWlzySNsabRlGKJIPyigZuO5Juo2teaZyFB4Z0OE_xIMFp7wYik-o4-JaFAkYXSBPmCHsvKFDE7PuJWgkYIAOzsUF71lXLACYJxrUzJ_eNlCbmcdwUAjxWCAgXlES5-hAeL_a30MYyZuYyW-u4wqtThaueALooHCuaFaWlYFIxsq75ZdGRzAoUTSQIguSZl7mllNjDnLxqmMaPzbjhFFlNLMBFXtqptHed81182rKzmyXmqKHLR4f7_yQnHUm9pBRDzHhvCkTupQ';
  static String failedPopupDesc='Something went wrong please try again';
  static String successSubscribedPopupDesc='you have succefully subscribed';
  static String failedPopupTitle='Failed';
  static String successSubscribedTitle='Successfully subscribed';

  static String tradeStartPopupDesc='you have succefully started trade';
  static String tradeStartPopupTitle='Successfully started';
   static String tradePausedPopupDesc='you have succefully paused trade';
  static String tradePausedPopupTitle='Successfully paused';
   static String tradeStopPopupDesc='you have succefully stopped trade';
  static String tradeStopPopupTitle='Successfully stopped';

  static String disclaimer='Disclaimer';
  static String pauseTradeCheckbox='I agree that I want to pause trading and I will be responsible for any potential loss due to this action.';
  static String pauseTradePopupTitle='You are about to perform a risky action. Are you sure you want to pause the trade? If so, this can lead to loss of money on your behalf. Keep in mind that you will be responsible for your losses yourself if you pause the trade at this point.';
  static String stopTradeCheckbox='I agree that I want to stop trading and I will be responsible for any potential loss due to this action.';
  static String stopTradePopupTitle="You are about to perform a risky action. Are you sure you want to stop the trade? If so, this can lead to loss of money on your behalf. Keep in mind that you will be responsible of your losses yourself, if you stop the trade at this point.";


}